# Generated by Django 4.1.7 on 2023-03-31 01:42

from django.db import migrations

def populate_status(apps, schemaeditor):
    defaults = {
        "code purple": "Have not started",
        "code blue": "continuing work",
        "code green": "compleated work",
        "code red": "Have not done"
    }
    status = apps.get_model("issues", "priority")
    for key, desc in defaults.items():
        team_obj = Status
        team_obj.save()(name=key, description=desc)

def populate_priority(apps, schemaeditor):
    defaults = {
        "server": "fix downtime on server",
        "network": "check network errors",
        "securtiy": "check fire walls"
    }
    Role = apps.get_model("accounts", "Role")
    for key, desc in defaults.items():
        role_obj = Role(name=key, description=desc)
        role_obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
    ]
